version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-test
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - test-network

  backend:
    container_name: backend-container-test
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    networks:
      - test-network
    depends_on:
      - db

  frontend:
    container_name: frontend-container-test
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        API_BASE_URL: ${API_BASE_URL}
    restart: always
    ports:
      - "3000:3000"
    networks:
      - test-network
    depends_on:
      - backend

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    ports:
      - "4444:4444"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
